### ISSUE TITLE
Writing a new post results in error "You need to subscribe to a SkyDB entry before updating it"

### ISSUE THREAD

**Issue by harej** [redsolver/skyfeed#11]
<img width="721" alt="Screen Shot 2020-11-16 at 10 53 33 AM" src="https://user-images.githubusercontent.com/150027/99295327-21f5db80-27fa-11eb-8cd5-605ca3989321.png">

Steps to reproduce:
1. Log in with a SkyID
2. Write a post in the new post box.
3. Click "Post"

This is on a brand new account with no other posts.

**Comment by harej** [comment]
Note that the error doesn't occur when I try to submit again.

**Comment by harej** [comment]
It may be worth noting, this was my first (attempt at a) post and subsequent posts (post attempts) succeeded.

**Comment by redsolver** [comment]
Should be fixed now
