### ISSUE TITLE
See your following and followers

### ISSUE THREAD

**Issue by TacoByte** [redsolver/skyfeed#25]
I got a notification that someone had followed me. I clicked OK to add him to my followers list. But, now, I can't find this user anywhere. It looks like I don't know anyone who is following him, so he is not being recommended to me. I can see that my Followers number got larger, but I can't click either of my Following or Followers numbers to expand the list.

**Comment by redsolver** [comment]
Working on it :+1: 
![image](https://user-images.githubusercontent.com/30355444/99900950-4bf44580-2cb3-11eb-8bbb-4c72f4513bdd.png)

**Comment by redsolver** [comment]
Added in newest beta. (Published in 1-2 hours)
